"""LDD detailed land-use legend — 96 codes (LU_CODE) → main type + TH/EN name.

AUTO-GENERATED from LU_BKK_2566.dbf (LDD Bangkok 2566). Do not hand-edit;
regenerate via data/ldd/generate_ldd_codes.py if the classification changes.
"""

# LU_CODE -> (l1_value 1-5, name_th, name_en). l1_value ยึด LUL1_CODE (U/A/F/W/M).
LDD_LU_CODES = {
    "A001": (2, "เกษตรผสมผสาน/ไร่นาสวนผสม", "Integrated farm/Diversified farm"),
    "A100": (2, "นาร้าง", "Abandoned paddy field"),
    "A101": (2, "นาข้าว", "Active paddy field"),
    "A300": (2, "ไม้ยืนต้นร้าง/เสื่อมโทรม", "Abandoned perenial"),
    "A300/A400": (2, "ไม้ยืนต้นร้าง/เสื่อมโทรม/ไม้ผลร้าง/เสื่อมโทรม", "Abandoned perennial/Abandoned orchard"),
    "A301": (2, "ไม้ยืนต้นผสม", "Mixed perennial"),
    "A301/A411": (2, "ไม้ยืนต้นผสม/กล้วย", "Mixed perennial/Banana"),
    "A303": (2, "ปาล์มน้ำมัน", "Oil palm"),
    "A303/A401": (2, "ปาล์มน้ำมัน/ไม้ผลผสม", "Oil plam/Mixed orchard"),
    "A303/A405": (2, "ปาล์มน้ำมัน/มะพร้าว", "Oil palm/Coconut"),
    "A304": (2, "ยูคาลิปตัส", "Eucalyptus"),
    "A305": (2, "สัก", "Teak"),
    "A306": (2, "สะเดา", "Magosa"),
    "A308": (2, "กระถิน", "Acacia"),
    "A315": (2, "ไผ่ปลูกเพื่อการค้า", "Bamboo"),
    "A315/A407": (2, "ไผ่ปลูกเพื่อการค้า/มะม่วง", "Bamboo/Mango"),
    "A315/A411": (2, "ไผ่ปลูกเพื่อการค้า/กล้วย", "Bamboo/Banana"),
    "A317": (2, "หมาก", "Betel palm"),
    "A317/A405": (2, "หมาก/มะพร้าว", "Betel palm/Coconut"),
    "A321": (2, "ยมหอม มะฮอกกานี", "Indian mahogany, Broad leaf  mahogany"),
    "A400": (2, "ไม้ผลร้าง/เสื่อมโทรม", "Abandoned orchard"),
    "A401": (2, "ไม้ผลผสม", "Mixed orchard"),
    "A402": (2, "ส้ม", "Orange"),
    "A405": (2, "มะพร้าว", "Coconut"),
    "A405/A407": (2, "มะพร้าว/มะม่วง", "Coconut/Mango"),
    "A405/A411": (2, "มะพร้าว/กล้วย", "Coconut/Banana"),
    "A405/A422": (2, "มะพร้าว/มะนาว", "Coconut/Lime"),
    "A405/A902": (2, "มะพร้าว/สถานที่เพาะเลี้ยงปลา", "Coconut/Fish farm"),
    "A407": (2, "มะม่วง", "Mango"),
    "A407/A411": (2, "มะม่วง/กล้วย", "Mango/Banana"),
    "A407/A417": (2, "มะม่วง/กระท้อน", "Mango/Santol"),
    "A407/A419": (2, "มะม่วง/มังคุด", "Mango/Mangosteen"),
    "A411": (2, "กล้วย", "Banana"),
    "A411/A414": (2, "กล้วย/ฝรั่ง", "Banana/Guava"),
    "A411/A416": (2, "กล้วย/ขนุน", "Banana/Jack fruit"),
    "A411/A422": (2, "กล้วย/มะนาว", "Banana/Lime"),
    "A411/A427": (2, "กล้วย/ส้มโอ", "Banana/Pomelo"),
    "A411/A503": (2, "กล้วย/ไม้ดอก", "Banana/Floricultural/Ornamental plant"),
    "A414": (2, "ฝรั่ง", "Guava"),
    "A422": (2, "มะนาว", "Lime"),
    "A422/A427": (2, "มะนาว/ส้มโอ", "Lime/Pomelo"),
    "A424": (2, "มะขามเทศ", "Manila tamarind"),
    "A426": (2, "แก้วมังกร", "Dragon fruit"),
    "A429": (2, "มะปราง มะยงชิด", "Marian plum"),
    "A500": (2, "พืชสวนร้าง/เสื่อมโทรม", "Abandoned horticulture"),
    "A502": (2, "พืชผัก", "Truck crop"),
    "A503": (2, "ไม้ดอก ไม้ประดับ", "Floricultural/Ornamental plant"),
    "A510": (2, "นาหญ้า", "Grass plantation"),
    "A700/A900": (2, "โรงเรือนร้าง/สถานที่เพาะเลี้ยงสัตว์น้ำร้าง", "Abandoneded farm house/Abandoned aquaculture land"),
    "A701": (2, "ทุ่งหญ้าเลี้ยงสัตว์", "Pasture"),
    "A703": (2, "โรงเรือนเลี้ยงสัตว์ปีก", "Poultry  farm house"),
    "A703/A902": (2, "โรงเรือนเลี้ยงสัตว์ปีก/สถานที่เพาะเลี้ยงปลา", "Poultry  farm house/Fish farm"),
    "A800": (2, "พืชน้ำร้าง", "Abandoned aquatic plant"),
    "A801": (2, "พืชน้ำผสม", "Mixed aquatic plant"),
    "A803": (2, "บัว", "Lotus"),
    "A806": (2, "ผักบุ้ง", "Water spinach"),
    "A807": (2, "ผักกะเฉด", "Water mimosa"),
    "A900": (2, "สถานที่เพาะเลี้ยงสัตว์น้ำร้าง", "Abandoned aquaculture land"),
    "A901": (2, "สถานที่เพาะเลี้ยงสัตว์น้ำผสม", "Mixed aquacultural land"),
    "A902": (2, "สถานที่เพาะเลี้ยงปลา", "Fish farm"),
    "A903": (2, "สถานที่เพาะเลี้ยงกุ้ง", "Shrimp farm"),
    "F300": (3, "ป่าชายเลนรอสภาพฟื้นฟู", "Disturbed mangrove  forest"),
    "F301": (3, "ป่าชายเลนสมบูรณ์", "Dense mangrove  forest"),
    "M101": (5, "ทุ่งหญ้าธรรมชาติ", "Grass"),
    "M102": (5, "ทุ่งหญ้าสลับไม้พุ่ม/ไม้ละเมาะ", "Shrubland"),
    "M201": (5, "พื้นที่ลุ่ม", "Marsh and Swamp"),
    "M300": (5, "เหมืองเก่า บ่อขุดเก่า", "Abandoned mine, Pit"),
    "M304": (5, "บ่อดิน", "Soil pit"),
    "M401": (5, "พื้นที่กองวัสดุ", "Material dump"),
    "M405": (5, "พื้นที่ถม", "Landfill"),
    "M701": (5, "ที่ทิ้งขยะ", "Garbage dump"),
    "U101": (1, "ตัวเมืองและย่านการค้า", "City, Town, Commercial"),
    "U200": (1, "หมู่บ้าน/ที่ดินจัดสรรร้าง", "Abandoned village"),
    "U201": (1, "หมู่บ้านบนพื้นราบ", "Village"),
    "U201/A401": (1, "หมู่บ้านบนพื้นราบ/ไม้ผลผสม", "Village/Mixed orchard"),
    "U301": (1, "สถานที่ราชการและสถาบันต่าง ๆ", "Institutional land"),
    "U401": (1, "สนามบิน", "Airport"),
    "U402": (1, "สถานีรถไฟ", "Railway station"),
    "U403": (1, "สถานีขนส่ง", "Bus station"),
    "U404": (1, "ท่าเรือ", "Harbour"),
    "U405": (1, "ถนน", "Road"),
    "U406": (1, "ทางรถไฟ", "Railway"),
    "U500": (1, "พื้นที่อุตสาหกรรมร้าง", "Abandoned industrial land"),
    "U501": (1, "นิคมอุตสาหกรรม", "Industrial estate"),
    "U502": (1, "โรงงานอุตสาหกรรม", "Factory"),
    "U601": (1, "สถานที่พักผ่อนหย่อนใจ", "Recreation area"),
    "U602": (1, "รีสอร์ท โรงแรม เกสต์เฮ้าส์", "Resort, Hotel, Guesthouse"),
    "U603": (1, "สุสาน ป่าช้า", "Cemetery"),
    "U605": (1, "สถานีบริการน้ำมัน", "Gasoline Station"),
    "U700": (1, "สนามกอล์ฟร้าง", "Abandoned golf course"),
    "U701": (1, "สนามกอล์ฟ", "Golf course"),
    "W101": (4, "แม่น้ำ ลำห้วย ลำคลอง", "River, Canal"),
    "W102": (4, "หนอง บึง ทะเลสาบ", "Lake, Lagoon"),
    "W103": (4, "ทะเล", "Ocean"),
    "W202": (4, "บ่อน้ำในไร่นา", "Farm pond"),
    "W203": (4, "คลองชลประทาน", "Irrigation canal"),
}
